telegram:
  source_chat_id: 7489921626
  destination_chat_ids:
    - -1003627702109
    - -1003754466935
    - -1003810019222
    - -1003858568453
    - -1003614040450
    - -1003650889221
    - -1003877471249
    - -1003867751629
    - -1003675022042
    - -1003739256247
    - -1003885693388
    - -1003885693388
    - -1003817466579
    - -1003708102924
  keywords:
